version: "2.1"
services:
  app-frontend:
    image: node:6.10-slim
    working_dir: /usr/src
    ports:
      - "8286:8286"
    volumes:
      - ./src/app-frontend:/usr/src
      - ./nginx/srv/dist:/usr/src/dist
      - /var/cache/tpsp-demo-node-modules:/usr/src/node_modules
    entrypoint: yarn
    command: run dev-server
  nginx:
    image: nginx:1.10
    ports:
      - "8080:443"
    links:
      - api-server
    volumes:
      - ./nginx/srv/dist/:/srv/dist/
      - ./nginx/etc/nginx/includes/:/etc/nginx/includes/
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  api-server:
    image: openjdk:8-jre
    ports:
      - "8777:8777"
    volumes:
      - ./src/app-backend/:/usr/src
      - ./src/app-backend/.sbt:/root/.sbt
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=geotrellis
    working_dir: /usr/src
    entrypoint: ./sbt
    command: ~server/reStart
